### PR TITLE
Adds full filepath for webcam images

### PR DESCRIPTION
**Pull request by JoonasMelin**
I had issues with the webcam images not found (the open function in the api fails as the images are in "/usr/local/lib/python2.7/dist-packages/bumblebee/images/" and the open function is given only the file name). I fixed this on my system by using the full path to the image.

Please see if the change makes any sense to you as I only tested the pip version on ubuntu 14.04 (as running the git version directly proved to be slightly challenging).

Some errors still remain though, as for example the cameracontroll seems to check for the existence of the output, but that fails, resulting on errors like: 
[2015-01-13 11:12:39,157] INFO: Webcam Command: exec /usr/bin/fswebcam -q --jpeg 60 -d '/dev/video1' -r 640x480 --title 'mf2 :: BotQueue.com' --set brightness=50% --set contrast=50% '/usr/local/lib/python2.7/dist-packages/bumblebee/images/bot-590.jpg'
[2015-01-13 11:12:39,668] ERROR: Webcam: stat: No such file or directory
[2015-01-13 11:12:39,668] ERROR: Webcam: 
[2015-01-13 11:12:39,668] ERROR: Errors detected.  Bailing.

### CODE REVIEW

**Comment by Jnesselr** [comment]
Apparently, there are multiple places I missed this. I need to do some testing, but I've got a fix planned. I'm trying to rework how cameras are accessed and handled, but that won't be done until the second API is done.

Also, if you installed the pip package as root, but don't run the client as root, then it currently won't work. I've got a proposed fix, but I don't currently like it and I'm looking for a better solution.

Could you elaborate on the issues you had running from git?

**Comment by JoonasMelin** [comment]
Running the git package was purely an user mistake as I didnt figure out that I had to run it with the -m handle. This does however cause some conflicts as I have the pip version installed and if I run the git version from any other folder, the pip version will be discovered first (as its on the PYTHONPATH) 

But anyway, those are really minor issues.

**Comment by JoonasMelin** [comment]
I fixed some additional issues on my fork. The camera control fixes were essential to get the calling command right (simple typo fix). I also fixed the relative import on the device scan as that was making the client freeze. I am not sure about the changes to the updateHomeBase fix as that was just something that I suspected might be causing issues on some cases.

These are of course more or less quick and dirty fixes to get things running, but just letting you know.

**Comment by Jnesselr** [comment]
So I've been trying to decide the best way to handle this, and I think the camera control should always get the full path (or assume current working directory). In reality, we should probably make the working directory something like "~/.config/botqueue/" and just not worry about all the full path stuff.

What do you think? 

Thanks for the command line fix!

**Comment by JoonasMelin** [comment]
I also feel like the approach on giving the actual image path to camera control is a good idea, as I think that many use cases make the relative path kind of unpredictable (running from /usr/bin for example).

Other approach would be to make the camera controls deal with paths by asking the image paths from the hive, but I feel this might be kind of risky in case you actually feed an path to the function and could generate many bugs.

The way the gcode file download is currently handled by appending the cachedir to the outputname seems like a great way to go. Saving the photos seems like a logical choice. Another option might be something like /tmp/botqueue (this would work in case the user does not have a home folder for some odd reason).

**Comment by peterus** [comment]
Hi, is it possible to merge here some stuff in to the mainline? I was changing it already many times in my local runtime. It is some kind of annoying...
Now I wanted to do an pull request, but I found this open request already.
If you don't have the time, i can create a quick work around for the directory problem. But I would like to have this in in the next days...

**Comment by Jnesselr** [comment]
So, fun story guys. You're gonna love it. I hope. Please don't eat me.

Okay, so I was actually looking over this pull request in an urgent care clinic originally some months ago. I had a migraine and was actually given some medicine to help with that that promptly knocked me out for the next couple of days. I don't remember posting on the 22nd at all.

I'm currently going through and refactoring some code. Hopefully I'll be able to fix this issue in a bit. For now, I'm going to merge in these changes (untested since I can't test it right now) because it looks correct. I'm not going to do a pip release until I refactor the stuff I'm working on now, though.

**Comment by peterus** [comment]
Sorry if i was a little bit harsh yesterday! I know this kind of medicine, my girlfriend is also sometimes taking tablets like this and than she is also totally away.

I was testing the changes yesterday, and i can confirm that the are working for now :)
If you need help in implementing new features just ping me, i have already some ideas that i would like to add.

**Pull request merged**
